#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef STRIPE_SWIFT_PROXY_SWIFT_H
#define STRIPE_SWIFT_PROXY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import StripePayments;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Stripe_Swift_Proxy",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface NSNumber (SWIFT_EXTENSION(Stripe_Swift_Proxy))
@property (nonatomic, readonly) enum STPCardBrand cardBrand;
@end

@class NSString;
SWIFT_CLASS_NAMED("TSPAddressDetails")
@interface TSPAddressDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable line1;
@property (nonatomic, copy) NSString * _Nullable line2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLine1:(NSString * _Nullable)line1 line2:(NSString * _Nullable)line2 city:(NSString * _Nullable)city state:(NSString * _Nullable)state postalCode:(NSString * _Nullable)postalCode country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPBillingDetails")
@interface TSPBillingDetails : NSObject
@property (nonatomic, strong) TSPAddressDetails * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAddress:(TSPAddressDetails * _Nullable)address email:(NSString * _Nullable)email name:(NSString * _Nullable)name phone:(NSString * _Nullable)phone OBJC_DESIGNATED_INITIALIZER;
@end

@class TSPSAppearanceFont;
@class TSPSAppearanceColors;
@class TSPSAppearancePrimaryButton;
@class TSPSAppearanceShadow;
SWIFT_CLASS_NAMED("TSPSAppearance")
@interface TSPSAppearance : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) TSPSAppearance * _Nonnull default_;)
+ (TSPSAppearance * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) TSPSAppearanceFont * _Nonnull font;
@property (nonatomic, readonly, strong) TSPSAppearanceColors * _Nonnull colors;
@property (nonatomic, readonly, strong) TSPSAppearancePrimaryButton * _Nonnull primaryButton;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, readonly, strong) TSPSAppearanceShadow * _Nonnull shadow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS_NAMED("TSPSAppearanceColors")
@interface TSPSAppearanceColors : NSObject
@property (nonatomic, strong) UIColor * _Nullable primary;
@property (nonatomic, strong) UIColor * _Nullable background;
@property (nonatomic, strong) UIColor * _Nullable componentBackground;
@property (nonatomic, strong) UIColor * _Nullable componentBorder;
@property (nonatomic, strong) UIColor * _Nullable componentDivider;
@property (nonatomic, strong) UIColor * _Nullable text;
@property (nonatomic, strong) UIColor * _Nullable textSecondary;
@property (nonatomic, strong) UIColor * _Nullable componentText;
@property (nonatomic, strong) UIColor * _Nullable componentPlaceholderText;
@property (nonatomic, strong) UIColor * _Nullable icon;
@property (nonatomic, strong) UIColor * _Nullable danger;
@property (nonatomic, strong) UIColor * _Nullable warning;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
SWIFT_CLASS_NAMED("TSPSAppearanceFont")
@interface TSPSAppearanceFont : NSObject
@property (nonatomic, strong) UIFont * _Nullable base;
@property (nonatomic) CGFloat sizeScaleFactor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSAppearancePrimaryButton")
@interface TSPSAppearancePrimaryButton : NSObject
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, readonly, strong) TSPSAppearanceShadow * _Nonnull shadow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSAppearanceShadow")
@interface TSPSAppearanceShadow : NSObject
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) CGSize offset;
@property (nonatomic) CGFloat radius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PKPaymentSummaryItem;
@class TSPSApplePayConfigurationHandlers;
SWIFT_CLASS_NAMED("TSPSApplePayConfiguration")
@interface TSPSApplePayConfiguration : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantId;
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantCountryCode;
@property (nonatomic, readonly) PKPaymentButtonType buttonType;
@property (nonatomic, readonly, copy) NSArray<PKPaymentSummaryItem *> * _Nullable paymentSummaryItems;
@property (nonatomic, readonly, strong) TSPSApplePayConfigurationHandlers * _Nullable customHandlers;
- (nonnull instancetype)initWithMerchantId:(NSString * _Nonnull)merchantId merchantCountryCode:(NSString * _Nonnull)merchantCountryCode buttonType:(PKPaymentButtonType)buttonType paymentSummaryItems:(NSArray<PKPaymentSummaryItem *> * _Nullable)paymentSummaryItems customHandlers:(TSPSApplePayConfigurationHandlers * _Nullable)customHandlers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("TSPSApplePayConfigurationHandlers")
@interface TSPSApplePayConfigurationHandlers : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TSPSCardBrand, open) {
  TSPSCardBrandVisa = 0,
  TSPSCardBrandAmex = 1,
  TSPSCardBrandMasterCard = 2,
  TSPSCardBrandDiscover = 3,
  TSPSCardBrandJCB = 4,
  TSPSCardBrandDinersClub = 5,
  TSPSCardBrandUnionPay = 6,
  TSPSCardBrandUnknown = 7,
};

@class TSPSCustomerConfiguration;
enum TSPSUserInterfaceStyle : NSInteger;
SWIFT_CLASS_NAMED("TSPSConfiguration")
@interface TSPSConfiguration : NSObject
@property (nonatomic, copy) NSString * _Nullable merchantDisplayName;
@property (nonatomic, strong) TSPSCustomerConfiguration * _Nullable customer;
@property (nonatomic, strong) UIColor * _Nullable primaryButtonColor;
@property (nonatomic, strong) TSPSAppearance * _Nonnull appearance;
@property (nonatomic, copy) NSString * _Nullable returnURL;
@property (nonatomic) BOOL allowsDelayedPaymentMethods;
@property (nonatomic) enum TSPSUserInterfaceStyle userInterfaceStyle;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable paymentMethodOrder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSCustomerConfiguration")
@interface TSPSCustomerConfiguration : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull ephemeralKeySecret;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id ephemeralKeySecret:(NSString * _Nonnull)ephemeralKeySecret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TSPSPaymentOption;
enum TSPSPaymentSheetResult : NSInteger;
@class NSCoder;
@class TSPSPaymentSheetFlowController;
SWIFT_CLASS_NAMED("TSPSPaymentButton")
@interface TSPSPaymentButton : UIButton
@property (nonatomic, copy) void (^ _Nullable onPaymentOptionChanged)(TSPSPaymentOption * _Nullable);
@property (nonatomic, copy) void (^ _Nullable onPaymentCompletion)(enum TSPSPaymentSheetResult, NSError * _Nullable);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)configureWith:(TSPSPaymentSheetFlowController * _Nonnull)flowController;
@end

@class TSPSPaymentMethod;
@class NSDate;
SWIFT_CLASS_NAMED("TSPSPaymentIntent")
@interface TSPSPaymentIntent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientSecret;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull amount;
@property (nonatomic, readonly, copy) NSString * _Nonnull currency;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, strong) TSPSPaymentMethod * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSDate * _Nonnull created;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TSPSPaymentMethodType : NSInteger;
@class TSPSPaymentMethodCard;
SWIFT_CLASS_NAMED("TSPSPaymentMethod")
@interface TSPSPaymentMethod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly) enum TSPSPaymentMethodType type;
@property (nonatomic, readonly, strong) TSPBillingDetails * _Nullable billingDetails;
@property (nonatomic, readonly, strong) TSPSPaymentMethodCard * _Nullable card;
@property (nonatomic, readonly, copy) NSDate * _Nullable created;
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("TSPSPaymentMethodCard")
@interface TSPSPaymentMethodCard : NSObject
@property (nonatomic, readonly) enum TSPSCardBrand brand;
@property (nonatomic, readonly, copy) NSString * _Nullable last4;
@property (nonatomic, readonly, strong) NSNumber * _Nullable expiryMonth;
@property (nonatomic, readonly, strong) NSNumber * _Nullable expiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable funding;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSPSPaymentMethodType, open) {
  TSPSPaymentMethodTypeCard = 0,
  TSPSPaymentMethodTypeCardPresent = 1,
  TSPSPaymentMethodTypeIDEAL = 2,
  TSPSPaymentMethodTypeSEPA = 3,
  TSPSPaymentMethodTypeAUBECSDebit = 4,
  TSPSPaymentMethodTypeBacsDebit = 5,
  TSPSPaymentMethodTypeSofort = 6,
  TSPSPaymentMethodTypeUPI = 7,
  TSPSPaymentMethodTypeNetBanking = 8,
  TSPSPaymentMethodTypeUnknown = 9,
};

@class UIImage;
SWIFT_CLASS_NAMED("TSPSPaymentOption")
@interface TSPSPaymentOption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, readonly, strong) UIImage * _Nonnull image;
- (nonnull instancetype)initWithLabel:(NSString * _Nonnull)label image:(UIImage * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIViewController;
@class NSError;
SWIFT_CLASS_NAMED("TSPSPaymentSheet")
@interface TSPSPaymentSheet : NSObject
- (nonnull instancetype)initWithPaymentIntentClientSecret:(NSString * _Nonnull)paymentIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration;
- (nonnull instancetype)initWithSetupIntentClientSecret:(NSString * _Nonnull)setupIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration;
+ (void)resetCustomer;
- (void)presentFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(enum TSPSPaymentSheetResult, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSPaymentSheetFlowController")
@interface TSPSPaymentSheetFlowController : NSObject
+ (void)createWithPaymentIntentClientSecret:(NSString * _Nonnull)paymentIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration completion:(void (^ _Nonnull)(TSPSPaymentSheetFlowController * _Nullable, NSError * _Nullable))completion;
+ (void)createWithSetupIntentClientSecret:(NSString * _Nonnull)setupIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration completion:(void (^ _Nonnull)(TSPSPaymentSheetFlowController * _Nullable, NSError * _Nullable))completion;
- (void)presentPaymentOptionsFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(void))completion;
- (void)confirmFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(enum TSPSPaymentSheetResult, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TSPSPaymentSheetResult, open) {
  TSPSPaymentSheetResultCompleted = 0,
  TSPSPaymentSheetResultCanceled = 1,
  TSPSPaymentSheetResultFailed = 2,
};

SWIFT_CLASS_NAMED("TSPSSetupIntent")
@interface TSPSSetupIntent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientSecret;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, strong) TSPSPaymentMethod * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSDate * _Nonnull created;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSPSUserInterfaceStyle, open) {
  TSPSUserInterfaceStyleAutomatic = 0,
  TSPSUserInterfaceStyleAlwaysLight = 1,
  TSPSUserInterfaceStyleAlwaysDark = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef STRIPE_SWIFT_PROXY_SWIFT_H
#define STRIPE_SWIFT_PROXY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import StripePayments;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Stripe_Swift_Proxy",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface NSNumber (SWIFT_EXTENSION(Stripe_Swift_Proxy))
@property (nonatomic, readonly) enum STPCardBrand cardBrand;
@end

@class NSString;
SWIFT_CLASS_NAMED("TSPAddressDetails")
@interface TSPAddressDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable line1;
@property (nonatomic, copy) NSString * _Nullable line2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLine1:(NSString * _Nullable)line1 line2:(NSString * _Nullable)line2 city:(NSString * _Nullable)city state:(NSString * _Nullable)state postalCode:(NSString * _Nullable)postalCode country:(NSString * _Nullable)country OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPBillingDetails")
@interface TSPBillingDetails : NSObject
@property (nonatomic, strong) TSPAddressDetails * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable phone;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAddress:(TSPAddressDetails * _Nullable)address email:(NSString * _Nullable)email name:(NSString * _Nullable)name phone:(NSString * _Nullable)phone OBJC_DESIGNATED_INITIALIZER;
@end

@class TSPSAppearanceFont;
@class TSPSAppearanceColors;
@class TSPSAppearancePrimaryButton;
@class TSPSAppearanceShadow;
SWIFT_CLASS_NAMED("TSPSAppearance")
@interface TSPSAppearance : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong, getter=default) TSPSAppearance * _Nonnull default_;)
+ (TSPSAppearance * _Nonnull)default SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) TSPSAppearanceFont * _Nonnull font;
@property (nonatomic, readonly, strong) TSPSAppearanceColors * _Nonnull colors;
@property (nonatomic, readonly, strong) TSPSAppearancePrimaryButton * _Nonnull primaryButton;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, readonly, strong) TSPSAppearanceShadow * _Nonnull shadow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS_NAMED("TSPSAppearanceColors")
@interface TSPSAppearanceColors : NSObject
@property (nonatomic, strong) UIColor * _Nullable primary;
@property (nonatomic, strong) UIColor * _Nullable background;
@property (nonatomic, strong) UIColor * _Nullable componentBackground;
@property (nonatomic, strong) UIColor * _Nullable componentBorder;
@property (nonatomic, strong) UIColor * _Nullable componentDivider;
@property (nonatomic, strong) UIColor * _Nullable text;
@property (nonatomic, strong) UIColor * _Nullable textSecondary;
@property (nonatomic, strong) UIColor * _Nullable componentText;
@property (nonatomic, strong) UIColor * _Nullable componentPlaceholderText;
@property (nonatomic, strong) UIColor * _Nullable icon;
@property (nonatomic, strong) UIColor * _Nullable danger;
@property (nonatomic, strong) UIColor * _Nullable warning;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
SWIFT_CLASS_NAMED("TSPSAppearanceFont")
@interface TSPSAppearanceFont : NSObject
@property (nonatomic, strong) UIFont * _Nullable base;
@property (nonatomic) CGFloat sizeScaleFactor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSAppearancePrimaryButton")
@interface TSPSAppearancePrimaryButton : NSObject
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, readonly, strong) TSPSAppearanceShadow * _Nonnull shadow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSAppearanceShadow")
@interface TSPSAppearanceShadow : NSObject
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) CGSize offset;
@property (nonatomic) CGFloat radius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PKPaymentSummaryItem;
@class TSPSApplePayConfigurationHandlers;
SWIFT_CLASS_NAMED("TSPSApplePayConfiguration")
@interface TSPSApplePayConfiguration : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantId;
@property (nonatomic, readonly, copy) NSString * _Nonnull merchantCountryCode;
@property (nonatomic, readonly) PKPaymentButtonType buttonType;
@property (nonatomic, readonly, copy) NSArray<PKPaymentSummaryItem *> * _Nullable paymentSummaryItems;
@property (nonatomic, readonly, strong) TSPSApplePayConfigurationHandlers * _Nullable customHandlers;
- (nonnull instancetype)initWithMerchantId:(NSString * _Nonnull)merchantId merchantCountryCode:(NSString * _Nonnull)merchantCountryCode buttonType:(PKPaymentButtonType)buttonType paymentSummaryItems:(NSArray<PKPaymentSummaryItem *> * _Nullable)paymentSummaryItems customHandlers:(TSPSApplePayConfigurationHandlers * _Nullable)customHandlers OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("TSPSApplePayConfigurationHandlers")
@interface TSPSApplePayConfigurationHandlers : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TSPSCardBrand, open) {
  TSPSCardBrandVisa = 0,
  TSPSCardBrandAmex = 1,
  TSPSCardBrandMasterCard = 2,
  TSPSCardBrandDiscover = 3,
  TSPSCardBrandJCB = 4,
  TSPSCardBrandDinersClub = 5,
  TSPSCardBrandUnionPay = 6,
  TSPSCardBrandUnknown = 7,
};

@class TSPSCustomerConfiguration;
enum TSPSUserInterfaceStyle : NSInteger;
SWIFT_CLASS_NAMED("TSPSConfiguration")
@interface TSPSConfiguration : NSObject
@property (nonatomic, copy) NSString * _Nullable merchantDisplayName;
@property (nonatomic, strong) TSPSCustomerConfiguration * _Nullable customer;
@property (nonatomic, strong) UIColor * _Nullable primaryButtonColor;
@property (nonatomic, strong) TSPSAppearance * _Nonnull appearance;
@property (nonatomic, copy) NSString * _Nullable returnURL;
@property (nonatomic) BOOL allowsDelayedPaymentMethods;
@property (nonatomic) enum TSPSUserInterfaceStyle userInterfaceStyle;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable paymentMethodOrder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSCustomerConfiguration")
@interface TSPSCustomerConfiguration : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull ephemeralKeySecret;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id ephemeralKeySecret:(NSString * _Nonnull)ephemeralKeySecret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TSPSPaymentOption;
enum TSPSPaymentSheetResult : NSInteger;
@class NSCoder;
@class TSPSPaymentSheetFlowController;
SWIFT_CLASS_NAMED("TSPSPaymentButton")
@interface TSPSPaymentButton : UIButton
@property (nonatomic, copy) void (^ _Nullable onPaymentOptionChanged)(TSPSPaymentOption * _Nullable);
@property (nonatomic, copy) void (^ _Nullable onPaymentCompletion)(enum TSPSPaymentSheetResult, NSError * _Nullable);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)configureWith:(TSPSPaymentSheetFlowController * _Nonnull)flowController;
@end

@class TSPSPaymentMethod;
@class NSDate;
SWIFT_CLASS_NAMED("TSPSPaymentIntent")
@interface TSPSPaymentIntent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientSecret;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull amount;
@property (nonatomic, readonly, copy) NSString * _Nonnull currency;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, strong) TSPSPaymentMethod * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSDate * _Nonnull created;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TSPSPaymentMethodType : NSInteger;
@class TSPSPaymentMethodCard;
SWIFT_CLASS_NAMED("TSPSPaymentMethod")
@interface TSPSPaymentMethod : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly) enum TSPSPaymentMethodType type;
@property (nonatomic, readonly, strong) TSPBillingDetails * _Nullable billingDetails;
@property (nonatomic, readonly, strong) TSPSPaymentMethodCard * _Nullable card;
@property (nonatomic, readonly, copy) NSDate * _Nullable created;
@property (nonatomic, readonly, copy) NSString * _Nullable customerId;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("TSPSPaymentMethodCard")
@interface TSPSPaymentMethodCard : NSObject
@property (nonatomic, readonly) enum TSPSCardBrand brand;
@property (nonatomic, readonly, copy) NSString * _Nullable last4;
@property (nonatomic, readonly, strong) NSNumber * _Nullable expiryMonth;
@property (nonatomic, readonly, strong) NSNumber * _Nullable expiryYear;
@property (nonatomic, readonly, copy) NSString * _Nullable funding;
@property (nonatomic, readonly, copy) NSString * _Nullable country;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSPSPaymentMethodType, open) {
  TSPSPaymentMethodTypeCard = 0,
  TSPSPaymentMethodTypeCardPresent = 1,
  TSPSPaymentMethodTypeIDEAL = 2,
  TSPSPaymentMethodTypeSEPA = 3,
  TSPSPaymentMethodTypeAUBECSDebit = 4,
  TSPSPaymentMethodTypeBacsDebit = 5,
  TSPSPaymentMethodTypeSofort = 6,
  TSPSPaymentMethodTypeUPI = 7,
  TSPSPaymentMethodTypeNetBanking = 8,
  TSPSPaymentMethodTypeUnknown = 9,
};

@class UIImage;
SWIFT_CLASS_NAMED("TSPSPaymentOption")
@interface TSPSPaymentOption : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull label;
@property (nonatomic, readonly, strong) UIImage * _Nonnull image;
- (nonnull instancetype)initWithLabel:(NSString * _Nonnull)label image:(UIImage * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIViewController;
@class NSError;
SWIFT_CLASS_NAMED("TSPSPaymentSheet")
@interface TSPSPaymentSheet : NSObject
- (nonnull instancetype)initWithPaymentIntentClientSecret:(NSString * _Nonnull)paymentIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration;
- (nonnull instancetype)initWithSetupIntentClientSecret:(NSString * _Nonnull)setupIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration;
+ (void)resetCustomer;
- (void)presentFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(enum TSPSPaymentSheetResult, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TSPSPaymentSheetFlowController")
@interface TSPSPaymentSheetFlowController : NSObject
+ (void)createWithPaymentIntentClientSecret:(NSString * _Nonnull)paymentIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration completion:(void (^ _Nonnull)(TSPSPaymentSheetFlowController * _Nullable, NSError * _Nullable))completion;
+ (void)createWithSetupIntentClientSecret:(NSString * _Nonnull)setupIntentClientSecret configuration:(TSPSConfiguration * _Nonnull)configuration completion:(void (^ _Nonnull)(TSPSPaymentSheetFlowController * _Nullable, NSError * _Nullable))completion;
- (void)presentPaymentOptionsFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(void))completion;
- (void)confirmFrom:(UIViewController * _Nonnull)presentingViewController completion:(void (^ _Nonnull)(enum TSPSPaymentSheetResult, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TSPSPaymentSheetResult, open) {
  TSPSPaymentSheetResultCompleted = 0,
  TSPSPaymentSheetResultCanceled = 1,
  TSPSPaymentSheetResultFailed = 2,
};

SWIFT_CLASS_NAMED("TSPSSetupIntent")
@interface TSPSSetupIntent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull stripeId;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientSecret;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, strong) TSPSPaymentMethod * _Nullable paymentMethod;
@property (nonatomic, readonly, copy) NSDate * _Nonnull created;
@property (nonatomic, readonly) BOOL liveMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TSPSUserInterfaceStyle, open) {
  TSPSUserInterfaceStyleAutomatic = 0,
  TSPSUserInterfaceStyleAlwaysLight = 1,
  TSPSUserInterfaceStyleAlwaysDark = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
